<?php
/**
 * NullHome — Install Wizard
 *
 * Invoked automatically by the root index.php when config.php is not found.
 * Guides the user through:
 *   1. Checking folder write-permissions
 *   2. Detecting root vs. sub-folder installation
 *   3. Entering and validating MySQL credentials
 *   4. Writing config.php
 *   5. Creating all database tables via DatabaseValidationService
 */

$appRootDir = dirname(__DIR__);
$configPath = $appRootDir . '/config.php';
$canWrite   = is_writable($appRootDir);

// Detect whether the app is at the server root or inside a sub-folder.
// dirname('/index.php') === '/'  →  root install
// dirname('/nullhome/index.php') === '/nullhome'  →  sub-folder install
$scriptDir     = dirname($_SERVER['SCRIPT_NAME'] ?? '/index.php');
$isRootInstall = ($scriptDir === '/' || $scriptDir === '');
$installType   = $isRootInstall ? 'root' : 'sub-folder (' . htmlspecialchars($scriptDir) . ')';

$step      = 'form';   // 'form' | 'success'
$errors    = [];
$dbResults = [];

// ── Form defaults ────────────────────────────────────────────────────────────
$formHost = 'localhost';
$formName = 'nullhome';
$formUser = '';

// ── Handle POST submission ────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host    = trim($_POST['db_host'] ?? '');
    $name    = trim($_POST['db_name'] ?? '');
    $user    = trim($_POST['db_user'] ?? '');
    $pass    = $_POST['db_pass']      ?? '';
    $charset = 'utf8mb4';

    // Repopulate form with submitted values for error redisplay
    $formHost = htmlspecialchars($host ?: 'localhost');
    $formName = htmlspecialchars($name ?: 'nullhome');
    $formUser = htmlspecialchars($user);

    // Basic validation
    if ($host === '') {
        $errors[] = 'Database host is required.';
    }
    if ($name === '') {
        $errors[] = 'Database name is required.';
    }
    if ($user === '') {
        $errors[] = 'Database username is required.';
    }

    // Test the MySQL connection before touching the filesystem
    if (empty($errors)) {
        try {
            $dsn     = sprintf('mysql:host=%s;dbname=%s;charset=%s', $host, $name, $charset);
            $testPdo = new PDO($dsn, $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            unset($testPdo);
        } catch (PDOException $e) {
            $errors[] = 'Database connection failed: ' . $e->getMessage();
        }
    }

    // Write config.php and create tables
    if (empty($errors)) {
        if (!$canWrite) {
            $errors[] = 'Cannot write config.php — the application directory is not writable. '
                      . 'Fix permissions and re-run the wizard. '
                      . 'Example: chmod g+w ' . $appRootDir;
        } else {
            // Build config.php content
            $cfg = "<?php\n"
                 . "// Database configuration — generated by the install wizard\n"
                 . "define('DB_HOST',    " . var_export($host,    true) . ");\n"
                 . "define('DB_NAME',    " . var_export($name,    true) . ");\n"
                 . "define('DB_USER',    " . var_export($user,    true) . ");\n"
                 . "define('DB_PASS',    " . var_export($pass,    true) . ");\n"
                 . "define('DB_CHARSET', " . var_export($charset, true) . ");\n\n"
                 . "// Application root path\n"
                 . "define('APP_ROOT', __DIR__);\n";

            if (file_put_contents($configPath, $cfg) === false) {
                $errors[] = 'Failed to write config.php. Check directory permissions.';
            } else {
                // Define constants for this request (config.php was not loaded)
                defined('DB_HOST')    || define('DB_HOST',    $host);
                defined('DB_NAME')    || define('DB_NAME',    $name);
                defined('DB_USER')    || define('DB_USER',    $user);
                defined('DB_PASS')    || define('DB_PASS',    $pass);
                defined('DB_CHARSET') || define('DB_CHARSET', $charset);
                defined('APP_ROOT')   || define('APP_ROOT',   $appRootDir);

                // Sync all model tables
                require_once $appRootDir . '/modules/db/DB.php';
                require_once $appRootDir . '/modules/db/DatabaseValidationService.php';

                $svc        = new DatabaseValidationService();
                $validation = $svc->validate();
                $dbResults  = $validation['results'];

                if ($validation['success']) {
                    $step = 'success';
                } else {
                    $errors[] = 'Database setup incomplete: ' . htmlspecialchars($validation['error'] ?? '');
                    // Remove the partially-written config so the wizard can be retried
                    @unlink($configPath);
                }
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NullHome — Install Wizard</title>
    <link rel="stylesheet" href="/public/css/install.css">
</head>
<body>
<div class="wizard">

    <h1>NullHome</h1>
    <p class="subtitle">Install Wizard — set up your database and create config.php</p>

    <!-- ── Pre-flight checks ──────────────────────────────────────────────── -->
    <div class="checks">
        <div class="check-item">
            <span class="check-dot <?= $canWrite ? 'dot-ok' : 'dot-warn' ?>"></span>
            <span class="check-label">Folder writable</span>
            <span class="check-value">
                <?php if ($canWrite): ?>
                    Yes — config.php can be created
                <?php else: ?>
                    No — run: <code>chmod a+w <?= htmlspecialchars($appRootDir) ?></code>
                <?php endif ?>
            </span>
        </div>
        <div class="check-item">
            <span class="check-dot dot-info"></span>
            <span class="check-label">Install type</span>
            <span class="check-value"><?= $installType ?></span>
        </div>
        <?php if (!$isRootInstall): ?>
        <div class="check-item">
            <span class="check-dot dot-warn"></span>
            <span class="check-label">Sub-folder note</span>
            <span class="check-value">
                The app's JS uses absolute API paths (<code>/api/…</code>).
                For a sub-folder install, configure your web server to serve
                this directory at the root, or update <code>public/js/app.js</code>.
            </span>
        </div>
        <?php endif ?>
    </div>

    <?php if ($step === 'success'): ?>
    <!-- ── Success ──────────────────────────────────────────────────────── -->
    <div class="success-box">
        <h2>&#10003; Installation complete!</h2>
        <p>config.php has been created and all database tables are ready.</p>
    </div>

    <div class="card">
        <h2>Database tables</h2>
        <table class="table-results">
            <thead>
                <tr>
                    <th>Model</th>
                    <th>Table</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($dbResults as $row): ?>
                <tr>
                    <td><?= htmlspecialchars($row['model']) ?></td>
                    <td><code><?= htmlspecialchars($row['table']) ?></code></td>
                    <td class="<?= $row['status'] === 'ok' ? 'status-ok' : 'status-err' ?>">
                        <?= htmlspecialchars($row['status']) ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>

        <a class="btn-go" href="/">Open NullHome &rarr;</a>
    </div>

    <?php else: ?>
    <!-- ── DB credentials form ──────────────────────────────────────────── -->
    <?php if (!empty($errors)): ?>
    <div class="errors">
        <ul>
            <?php foreach ($errors as $err): ?>
            <li><?= htmlspecialchars($err) ?></li>
            <?php endforeach ?>
        </ul>
    </div>
    <?php endif ?>

    <form class="card" method="post">
        <h2>Database connection</h2>

        <div class="form-group">
            <label for="db_host">Host</label>
            <input type="text" id="db_host" name="db_host"
                   value="<?= $formHost ?>" required autocomplete="off">
        </div>

        <div class="form-group">
            <label for="db_name">Database name</label>
            <input type="text" id="db_name" name="db_name"
                   value="<?= $formName ?>" required autocomplete="off">
            <span class="hint">The database must already exist in MySQL.</span>
        </div>

        <div class="form-group">
            <label for="db_user">Username</label>
            <input type="text" id="db_user" name="db_user"
                   value="<?= $formUser ?>" required autocomplete="off">
        </div>

        <div class="form-group">
            <label for="db_pass">Password</label>
            <input type="password" id="db_pass" name="db_pass"
                   value="" autocomplete="new-password">
            <span class="hint">
                <?php if (!empty($errors)): ?>
                    Re-enter your password (not stored between attempts).
                <?php else: ?>
                    Leave blank if the user has no password.
                <?php endif ?>
            </span>
        </div>

        <button type="submit" class="btn-install"
                <?= $canWrite ? '' : 'disabled title="Fix folder permissions first"' ?>>
            Install NullHome
        </button>
    </form>
    <?php endif ?>

</div>
</body>
</html>
