<?php
/**
 * NullHome — Install Wizard
 *
 * Invoked automatically by the root index.php when config.php is not found.
 * Guides the user through:
 *   1. Checking folder write-permissions
 *   2. Detecting root vs. sub-folder installation
 *   3. Entering and validating MySQL credentials
 *   4. Writing config.php
 *   5. Creating all database tables via DatabaseValidationService
 */

$appRootDir = dirname(__DIR__);
$configPath = $appRootDir . '/config.php';
$canWrite   = is_writable($appRootDir);

// Detect whether the app is at the server root or inside a sub-folder.
// dirname('/index.php') === '/'  →  root install
// dirname('/nullhome/index.php') === '/nullhome'  →  sub-folder install
$scriptDir     = dirname($_SERVER['SCRIPT_NAME'] ?? '/index.php');
$isRootInstall = ($scriptDir === '/' || $scriptDir === '');
$installType   = $isRootInstall ? 'root' : 'sub-folder (' . htmlspecialchars($scriptDir) . ')';

$step      = 'form';   // 'form' | 'success'
$errors    = [];
$dbResults = [];

// ── Form defaults ────────────────────────────────────────────────────────────
$formHost = 'localhost';
$formName = 'nullhome';
$formUser = '';

// ── Handle POST submission ────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $host    = trim($_POST['db_host'] ?? '');
    $name    = trim($_POST['db_name'] ?? '');
    $user    = trim($_POST['db_user'] ?? '');
    $pass    = $_POST['db_pass']      ?? '';
    $charset = 'utf8mb4';

    // Repopulate form with submitted values for error redisplay
    $formHost = htmlspecialchars($host ?: 'localhost');
    $formName = htmlspecialchars($name ?: 'nullhome');
    $formUser = htmlspecialchars($user);

    // Basic validation
    if ($host === '') {
        $errors[] = 'Database host is required.';
    }
    if ($name === '') {
        $errors[] = 'Database name is required.';
    }
    if ($user === '') {
        $errors[] = 'Database username is required.';
    }

    // Test the MySQL connection before touching the filesystem
    if (empty($errors)) {
        try {
            $dsn     = sprintf('mysql:host=%s;dbname=%s;charset=%s', $host, $name, $charset);
            $testPdo = new PDO($dsn, $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
            unset($testPdo);
        } catch (PDOException $e) {
            $errors[] = 'Database connection failed: ' . $e->getMessage();
        }
    }

    // Write config.php and create tables
    if (empty($errors)) {
        if (!$canWrite) {
            $errors[] = 'Cannot write config.php — the application directory is not writable. '
                      . 'Fix permissions and re-run the wizard. '
                      . 'Example: chmod g+w ' . $appRootDir;
        } else {
            // Build config.php content
            $cfg = "<?php\n"
                 . "// Database configuration — generated by the install wizard\n"
                 . "define('DB_HOST',    " . var_export($host,    true) . ");\n"
                 . "define('DB_NAME',    " . var_export($name,    true) . ");\n"
                 . "define('DB_USER',    " . var_export($user,    true) . ");\n"
                 . "define('DB_PASS',    " . var_export($pass,    true) . ");\n"
                 . "define('DB_CHARSET', " . var_export($charset, true) . ");\n\n"
                 . "// Application root path\n"
                 . "define('APP_ROOT', __DIR__);\n";

            if (file_put_contents($configPath, $cfg) === false) {
                $errors[] = 'Failed to write config.php. Check directory permissions.';
            } else {
                // Define constants for this request (config.php was not loaded)
                defined('DB_HOST')    || define('DB_HOST',    $host);
                defined('DB_NAME')    || define('DB_NAME',    $name);
                defined('DB_USER')    || define('DB_USER',    $user);
                defined('DB_PASS')    || define('DB_PASS',    $pass);
                defined('DB_CHARSET') || define('DB_CHARSET', $charset);
                defined('APP_ROOT')   || define('APP_ROOT',   $appRootDir);

                // Sync all model tables
                require_once $appRootDir . '/db/DB.php';
                require_once $appRootDir . '/services/DatabaseValidationService.php';

                $svc        = new DatabaseValidationService();
                $validation = $svc->validate();
                $dbResults  = $validation['results'];

                if ($validation['success']) {
                    $step = 'success';
                } else {
                    $errors[] = 'Database setup incomplete: ' . htmlspecialchars($validation['error'] ?? '');
                    // Remove the partially-written config so the wizard can be retried
                    @unlink($configPath);
                }
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NullHome — Install Wizard</title>
    <style>
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

        :root {
            --bg:       #0f0f0f;
            --surface:  #1a1a1a;
            --surface2: #252525;
            --border:   #333;
            --text:     #e8e8e8;
            --muted:    #888;
            --accent:   #4a9eff;
            --ok:       #4caf50;
            --warn:     #ff9800;
            --danger:   #f44336;
            --radius:   6px;
        }

        body {
            font-family: system-ui, -apple-system, sans-serif;
            background: var(--bg);
            color: var(--text);
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: flex-start;
            padding: 2rem 1rem;
        }

        .wizard {
            width: 100%;
            max-width: 540px;
        }

        h1 {
            font-size: 1.5rem;
            font-weight: 700;
            color: var(--accent);
            margin-bottom: 0.25rem;
        }

        .subtitle {
            color: var(--muted);
            font-size: 0.875rem;
            margin-bottom: 1.75rem;
        }

        /* ── Status cards ──────────────────────────────────── */

        .checks {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
            margin-bottom: 1.5rem;
        }

        .check-item {
            display: flex;
            align-items: center;
            gap: 0.65rem;
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: var(--radius);
            padding: 0.65rem 0.9rem;
            font-size: 0.875rem;
        }

        .check-dot {
            width: 10px;
            height: 10px;
            border-radius: 50%;
            flex-shrink: 0;
        }

        .dot-ok   { background: var(--ok); }
        .dot-warn { background: var(--warn); }
        .dot-info { background: var(--accent); }

        .check-label { color: var(--muted); min-width: 160px; }
        .check-value { color: var(--text); }

        /* ── Form ──────────────────────────────────────────── */

        .card {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: var(--radius);
            padding: 1.5rem;
        }

        .card h2 {
            font-size: 1rem;
            font-weight: 600;
            margin-bottom: 1.25rem;
            color: var(--accent);
        }

        .form-group {
            display: flex;
            flex-direction: column;
            gap: 0.3rem;
            margin-bottom: 1rem;
        }

        .form-group label {
            font-size: 0.78rem;
            color: var(--muted);
        }

        .form-group input {
            background: var(--surface2);
            border: 1px solid var(--border);
            color: var(--text);
            padding: 0.5rem 0.7rem;
            border-radius: var(--radius);
            font-size: 0.875rem;
            outline: none;
            transition: border-color 0.15s;
            width: 100%;
        }

        .form-group input:focus { border-color: var(--accent); }

        .form-group .hint {
            font-size: 0.73rem;
            color: var(--muted);
        }

        .btn-install {
            display: block;
            width: 100%;
            margin-top: 0.5rem;
            padding: 0.6rem 1rem;
            background: var(--accent);
            border: none;
            border-radius: var(--radius);
            color: #fff;
            font-size: 0.9rem;
            font-weight: 600;
            cursor: pointer;
            transition: opacity 0.15s;
        }

        .btn-install:hover { opacity: 0.85; }

        /* ── Errors ────────────────────────────────────────── */

        .errors {
            background: rgba(244, 67, 54, 0.1);
            border: 1px solid var(--danger);
            border-radius: var(--radius);
            padding: 0.75rem 1rem;
            margin-bottom: 1.25rem;
            font-size: 0.85rem;
        }

        .errors ul { padding-left: 1.2rem; }
        .errors li { margin-bottom: 0.25rem; color: #ff8a80; }

        /* ── Success ───────────────────────────────────────── */

        .success-box {
            background: rgba(76, 175, 80, 0.1);
            border: 1px solid var(--ok);
            border-radius: var(--radius);
            padding: 1rem 1.25rem;
            margin-bottom: 1.25rem;
        }

        .success-box h2 {
            font-size: 1rem;
            color: var(--ok);
            margin-bottom: 0.4rem;
        }

        .success-box p { font-size: 0.875rem; color: var(--text); }

        .table-results {
            width: 100%;
            border-collapse: collapse;
            margin-top: 0.75rem;
            font-size: 0.82rem;
        }

        .table-results th,
        .table-results td {
            text-align: left;
            padding: 0.4rem 0.6rem;
            border-bottom: 1px solid var(--border);
        }

        .table-results th { color: var(--muted); font-weight: 500; }

        .status-ok   { color: var(--ok); }
        .status-err  { color: var(--danger); }

        .btn-go {
            display: inline-block;
            margin-top: 1rem;
            padding: 0.55rem 1.1rem;
            background: var(--accent);
            border: none;
            border-radius: var(--radius);
            color: #fff;
            font-size: 0.875rem;
            font-weight: 600;
            text-decoration: none;
            transition: opacity 0.15s;
        }

        .btn-go:hover { opacity: 0.85; }
    </style>
</head>
<body>
<div class="wizard">

    <h1>NullHome</h1>
    <p class="subtitle">Install Wizard — set up your database and create config.php</p>

    <!-- ── Pre-flight checks ──────────────────────────────────────────────── -->
    <div class="checks">
        <div class="check-item">
            <span class="check-dot <?= $canWrite ? 'dot-ok' : 'dot-warn' ?>"></span>
            <span class="check-label">Folder writable</span>
            <span class="check-value">
                <?php if ($canWrite): ?>
                    Yes — config.php can be created
                <?php else: ?>
                    No — run: <code>chmod a+w <?= htmlspecialchars($appRootDir) ?></code>
                <?php endif ?>
            </span>
        </div>
        <div class="check-item">
            <span class="check-dot dot-info"></span>
            <span class="check-label">Install type</span>
            <span class="check-value"><?= $installType ?></span>
        </div>
        <?php if (!$isRootInstall): ?>
        <div class="check-item">
            <span class="check-dot dot-warn"></span>
            <span class="check-label">Sub-folder note</span>
            <span class="check-value">
                The app's JS uses absolute API paths (<code>/api/…</code>).
                For a sub-folder install, configure your web server to serve
                this directory at the root, or update <code>app/js/app.js</code>.
            </span>
        </div>
        <?php endif ?>
    </div>

    <?php if ($step === 'success'): ?>
    <!-- ── Success ──────────────────────────────────────────────────────── -->
    <div class="success-box">
        <h2>&#10003; Installation complete!</h2>
        <p>config.php has been created and all database tables are ready.</p>
    </div>

    <div class="card">
        <h2>Database tables</h2>
        <table class="table-results">
            <thead>
                <tr>
                    <th>Model</th>
                    <th>Table</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($dbResults as $row): ?>
                <tr>
                    <td><?= htmlspecialchars($row['model']) ?></td>
                    <td><code><?= htmlspecialchars($row['table']) ?></code></td>
                    <td class="<?= $row['status'] === 'ok' ? 'status-ok' : 'status-err' ?>">
                        <?= htmlspecialchars($row['status']) ?>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>

        <a class="btn-go" href="/">Open NullHome &rarr;</a>
    </div>

    <?php else: ?>
    <!-- ── DB credentials form ──────────────────────────────────────────── -->
    <?php if (!empty($errors)): ?>
    <div class="errors">
        <ul>
            <?php foreach ($errors as $err): ?>
            <li><?= htmlspecialchars($err) ?></li>
            <?php endforeach ?>
        </ul>
    </div>
    <?php endif ?>

    <form class="card" method="post">
        <h2>Database connection</h2>

        <div class="form-group">
            <label for="db_host">Host</label>
            <input type="text" id="db_host" name="db_host"
                   value="<?= $formHost ?>" required autocomplete="off">
        </div>

        <div class="form-group">
            <label for="db_name">Database name</label>
            <input type="text" id="db_name" name="db_name"
                   value="<?= $formName ?>" required autocomplete="off">
            <span class="hint">The database must already exist in MySQL.</span>
        </div>

        <div class="form-group">
            <label for="db_user">Username</label>
            <input type="text" id="db_user" name="db_user"
                   value="<?= $formUser ?>" required autocomplete="off">
        </div>

        <div class="form-group">
            <label for="db_pass">Password</label>
            <input type="password" id="db_pass" name="db_pass"
                   value="" autocomplete="new-password">
            <span class="hint">
                <?php if (!empty($errors)): ?>
                    Re-enter your password (not stored between attempts).
                <?php else: ?>
                    Leave blank if the user has no password.
                <?php endif ?>
            </span>
        </div>

        <button type="submit" class="btn-install"
                <?= $canWrite ? '' : 'disabled title="Fix folder permissions first"' ?>>
            Install NullHome
        </button>
    </form>
    <?php endif ?>

</div>
</body>
</html>
